Repository honeycombio/beeline-nodejs, pull requests merged in 2021-12, with the labels that each got.

#502 Expand type definitions to include all libhoney options
  lib/api/libhoney.js
  lib/types.d.ts
Labels: type: enhancement, version: bump minor

#508 Prepare v3.1.0 release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: type: maintenance, version: bump minor

#510 maint: Enable linting for ts files (to lint types file)
  .eslintrc.json
  package-lock.json
  package.json
  tsconfig.json
Labels: type: maintenance, version: no bump

#513 maint: Add npm shield with link to npm package
  README.md
Labels: version: no bump, type: documentation, merge at will

#509 Further improvements to typescript types
  lib/types.d.ts
Labels: type: enhancement, version: bump minor

#515 add docker-compose config for test-worthy Postgres
  docker-compose.yaml
Labels: type: maintenance, version: no bump

#514 feat: accept both w3c and honeycomb propagation headers by default
  lib/instrumentation/trace-util.js
  lib/instrumentation/trace-util.test.js
Labels: type: enhancement, version: bump minor, merge at will

#516 Prepare v3.2.0
  CHANGELOG.md
  package-lock.json
  package.json
Labels: type: maintenance, version: no bump
