Repository honeycombio/beeline-nodejs, pull requests merged in 2021-01, with the labels that each got.

#287 Ensure fastify instrumentation honors the httpParserHook config
  lib/instrumentation/express.test.js
  lib/instrumentation/fastify.js
  lib/instrumentation/fastify.test.js
Labels: type: bug, version: bump patch

#288 Use the non-deprecated request.raw attribute
  lib/instrumentation/fastify.js
Labels: type: maintenance, version: bump patch

#295 add our custom action to manage project labels
  .github/dependabot.yml
  .github/workflows/apply-labels.yml
Labels: status: review needed, type: maintenance, version: no bump
