Repository honeycombio/beeline-nodejs, pull requests merged in 2021-09, with the labels that each got.

#438 Prepare v2.8.0
  CHANGELOG.md
  README.md
  RELEASING.md
  package-lock.json
  package.json
Labels: type: maintenance, version: no bump, status: review needed

#443 Add engines to package.json
  package.json
Labels: type: maintenance, version: no bump

#444 Update deprecation comments
  lib/api/index.js
  lib/api/libhoney.js
  lib/api/mock.js
  lib/propagation/index.js
  lib/types.d.ts
Labels: type: maintenance, version: bump patch

#450 Fix types on bindFunctionToTrace
  lib/types.d.ts
Labels: type: bug, version: bump patch

#347 Fix api.addContext so it works on the current span (not the root)
  lib/api/index.test.js
  lib/api/libhoney.js
  lib/api/mock.js
Labels: type: bug, version: bump major

#457 Remove deprecated APIs
  docs/API.md
  docs/CustomContext.md
  lib/api/index.js
  lib/api/index.test.js
  lib/api/libhoney.js
  lib/api/mock.js
  lib/instrumentation/express.test.js
  lib/instrumentation/fastify.test.js
  lib/instrumentation/http.test.js
  lib/instrumentation/trace-util.test.js
  lib/propagation/index.js
  lib/propagation/propagation.test.js
  lib/types.d.ts
Labels: type: maintenance, version: bump major

#465 clean up npm tarball
  package.json
Labels: type: maintenance, version: no bump
