Repository honeycombio/beeline-nodejs, pull requests merged in 2021-06, with the labels that each got.

#351 docs: show how to import beeline in TypeScript
  docs/API.md
Labels: docs, version: no bump

#379 Made sampleRate optional in the interface
  lib/types.d.ts
Labels: type: bug, version: bump patch

#360 Add node 16 to test matrix, switch to non-legacy circle images
  .circleci/config.yml
Labels: type: maintenance, version: no bump

#361 Fix: http(s) instrumentation URL arg
  lib/instrumentation/http.js
  lib/instrumentation/http.test.js
  lib/instrumentation/https.js
  lib/url-util.js
Labels: type: bug, version: bump patch
