Repository honeycombio/beeline-nodejs, pull requests merged in 2022-01, with the labels that each got.

#524 maint: clean up tests to reduce code duplication and fragility
  lib/instrumentation/child_process.test.js
  lib/instrumentation/express.test.js
  lib/instrumentation/fastify.test.js
  lib/instrumentation/pg.test.js
  lib/instrumentation/react-dom-server.test.js
Labels: type: maintenance, version: no bump

#530 Prepare v3.2.1 release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: type: maintenance, version: bump patch

#532 Update vulnerable dependencies
  examples/node-tracing/package-lock.json
  package-lock.json
Labels: version: no bump

#533 Fix parser defaults
  lib/instrumentation/express.js
  lib/instrumentation/trace-util.js
  lib/instrumentation/trace-util.test.js
  lib/propagation/hooks.js
  lib/propagation/index.js
  lib/types.d.ts
Labels: type: bug, version: bump patch
