Repository honeycombio/beeline-nodejs, pull requests merged in 2024-03, with the labels that each got.

#726 feat: support classic ingest keys, upgrade to libhoney 4.2.0
  lib/api/index.js
  lib/api/index.test.js
  lib/api/libhoney.js
  lib/util.js
  package-lock.json
  package.json
Labels: type: enhancement, version: bump minor

#727 rel: Prepare v4.1.0 release
  CHANGELOG.md
  package-lock.json
  package.json
Labels: type: maintenance, no-changelog

#728 maint: add labels to release.yml for auto-generated grouping
  .github/release.yml
Labels: type: maintenance, version: no bump, no-changelog
